# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
a=np.random.randint(0,5,size=(3,3,3))
print("3x3x3 array with random values:\n",a)

3x3x3 array with random values:
 [[[0 2 4]
  [1 0 4]
  [0 2 0]]

 [[0 2 2]
  [0 2 4]
  [2 1 2]]

 [[4 3 4]
  [0 2 2]
  [1 1 1]]]


In [2]:
a.shape

(3, 3, 3)

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
b=np.diag([1,2,3,4],k=-1)
print("Output:\n",b)

Output:
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [4]:
b.shape

(5, 5)

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [5]:
c=np.zeros((8,8))
print(c)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [6]:
c[0:8:2,1:8:2]=1
c[1:8:2,0:8:2]=1
print("Checkerboard pattern with 8x8 matrix:\n",c)

Checkerboard pattern with 8x8 matrix:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [7]:
c.shape

(8, 8)

# 4. Normalize a 5x5 random matrix

In [8]:
x=np.random.random((5,5))
print("5x5 Random matrix:\n",x)

5x5 Random matrix:
 [[0.86955195 0.99346138 0.57246269 0.3637595  0.80655826]
 [0.23268287 0.36977124 0.58700649 0.91388896 0.60804351]
 [0.38186367 0.77346168 0.03985878 0.28702656 0.75549185]
 [0.20941629 0.33273541 0.85005727 0.5767394  0.44380261]
 [0.28349277 0.70232862 0.09556056 0.52956601 0.28056825]]


In [9]:
mag_x=np.linalg.norm(x)
print("Magnitude of matrix x:\n",mag_x)

Magnitude of matrix x:
 2.8881651402857087


In [10]:
y=np.divide(x,mag_x)
print("Noramlize Matrix:\n",y)

Noramlize Matrix:
 [[0.30107418 0.34397665 0.19820982 0.1259483  0.27926321]
 [0.08056425 0.12802981 0.20324547 0.31642545 0.21052934]
 [0.1322167  0.26780383 0.01380073 0.09938025 0.26158194]
 [0.07250842 0.1152065  0.29432433 0.19969059 0.15366248]
 [0.0981567  0.24317467 0.03308694 0.18335725 0.09714412]]


In [11]:
mag_y=np.linalg.norm(y)
print("Magnitude of normalize matrix:\n",mag_y)

Magnitude of normalize matrix:
 0.9999999999999999


- Magnitude of unit vector = 1

# 5.  How to find common values between two arrays?

In [12]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([4,5,6,7,8])
print("The common values between 2 arrays:\n",np.intersect1d(arr1,arr2))

The common values between 2 arrays:
 [4 5]


# 6.How to get the dates of yesterday, today and tomorrow?

In [13]:
yes=np.datetime64("today","D")-np.timedelta64(1,"D")
print("Yesterday's Date:",yes)

Yesterday's Date: 2020-07-28


In [14]:
today=np.datetime64("today","D")
print("Today's date:",today)

Today's date: 2020-07-29


In [15]:
tomm=np.datetime64("today","D")+np.timedelta64(1,"D")
print("Tommorow's date:",tomm)

Tommorow's date: 2020-07-30


# 7. Consider two random array A and B, check if they are equal

In [16]:
A=np.random.randint(5,size=(3,3))
print("Matrix A:\n",A)

Matrix A:
 [[4 3 1]
 [0 4 1]
 [1 4 4]]


In [17]:
B=np.random.randint(5,size=(3,3))
print("Matrix B:\n",B)

Matrix B:
 [[0 0 4]
 [1 3 2]
 [0 4 4]]


In [18]:
print("Result:",np.array_equal(A,B))

Result: False


In [19]:
print(np.array_equal([1,2],[1,2]))

True


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [20]:
arr5=np.random.random(10)
arr5

array([0.01610548, 0.43227282, 0.48125557, 0.03855831, 0.64129264,
       0.56035658, 0.4142692 , 0.38493263, 0.63534852, 0.69315474])

In [21]:
print("Max value Index :",np.argmax(arr5))

Max value Index : 9


In [22]:
arr5[9]=0
print("Result:\n",arr5)

Result:
 [0.01610548 0.43227282 0.48125557 0.03855831 0.64129264 0.56035658
 0.4142692  0.38493263 0.63534852 0.        ]


# 9. How to print all the values of an array?

In [23]:
np.set_printoptions(threshold=5)
arr3=np.arange(1000)
print("Output with truncation:",arr3)

Output with truncation: [  0   1   2 ... 997 998 999]


In [24]:
import sys
np.set_printoptions(threshold=sys.maxsize)
arr3=np.arange(1000)
print("Output with all the values:\n",arr3)

Output with all the values:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 2

# 10.Subtract the mean of each row of a matrix

In [25]:
s=np.array([[10,20,30],[40,50,60],[70,80,90]])
s

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [26]:
j=np.mean(s,axis=1)
print("Mean of each row:",j)

Mean of each row: [20. 50. 80.]


In [27]:
k=np.subtract(s,j)
print("Subtraction:\n",k)

Subtraction:
 [[-10. -30. -50.]
 [ 20.   0. -20.]
 [ 50.  30.  10.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [28]:
r1=np.array([1,2,3,4,1,8,8,8])
r1

array([1, 2, 3, 4, 1, 8, 8, 8])

In [29]:
r2=np.unique(r1,return_index=True)
r2

(array([1, 2, 3, 4, 8]), array([0, 1, 2, 3, 5], dtype=int32))

In [30]:
np.add.at(r1,[0,1,2,3,5],1)
r1

array([2, 3, 4, 5, 1, 9, 8, 8])

# 12.How to get the diagonal of a dot product?

In [31]:
v=np.array([[40,50],[60,70]])
w=np.array([[30,20],[10,20]])
g=np.dot(v,w)
print("dot product:\n",g)

dot product:
 [[1700 1800]
 [2500 2600]]


In [32]:
g.shape

(2, 2)

In [33]:
h=np.diag(g,k=0)

In [34]:
print("Diagonal of dot product:",h)

Diagonal of dot product: [1700 2600]


In [35]:
h.shape

(2,)

# 13.How to find the most frequent value in an array?

In [36]:
from statistics import mode
arr7=np.array([20,20,40,50,20,70,80,20])
arr7

array([20, 20, 40, 50, 20, 70, 80, 20])

In [37]:
print("Most frequent value in an array:",mode(arr7))

Most frequent value in an array: 20


# 14.How to get the n largest values of an array

In [38]:
arr8=np.array([50,45,10,15,25,35,30,20])
arr8

array([50, 45, 10, 15, 25, 35, 30, 20])

In [39]:
arr9=np.sort(arr8)
print(arr9)

[10 15 20 25 30 35 45 50]


In [40]:
print("Enter the number of largest values you want in an array:")
n=int(input())
print("Largest values:",arr9[-n:])

Enter the number of largest values you want in an array:
2
Largest values: [45 50]


# 15.How to create a record array from a regular array?

In [41]:
x1=np.array(["John","Keith","Mona"])
x1

array(['John', 'Keith', 'Mona'], dtype='<U5')

In [42]:
x2=np.array([30,25,20])
x2

array([30, 25, 20])

In [43]:
x3=np.array([95000.0,30000.0,15000.0])
x3

array([95000., 30000., 15000.])

In [44]:
rec_arr=np.core.records.fromarrays([x1,x2,x3],names="Name,Age,Salary")
rec_arr

rec.array([('John', 30, 95000.), ('Keith', 25, 30000.),
           ('Mona', 20, 15000.)],
          dtype=[('Name', '<U5'), ('Age', '<i4'), ('Salary', '<f8')])

In [45]:
rec_arr[1]

('Keith', 25, 30000.)

In [46]:
print("Name:",rec_arr["Name"])

Name: ['John' 'Keith' 'Mona']


In [47]:
print("Age:",rec_arr["Age"])

Age: [30 25 20]


In [48]:
print("Salary:",rec_arr["Salary"])

Salary: [95000. 30000. 15000.]
